from __future__ import annotations

import html


def render_html_from_markdown(md: str, title: str) -> str:
    # Inject a TOC marker for HTML only.
    html_input = "[TOC]\n\n" + md

    try:
        import markdown as mdlib

        body = mdlib.markdown(
            html_input,
            extensions=[
                "fenced_code",
                "tables",
                "toc",
                "sane_lists",
            ],
            output_format="html5",
        )
    except Exception:
        body = f"<pre>{html.escape(md)}</pre>"

    safe_title = html.escape(title)

    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{safe_title}</title>
  <style>
    :root {{
      --bg: #ffffff;
      --fg: #111827;
      --muted: #6b7280;
      --border: #e5e7eb;
      --codebg: #f6f8fa;
      --link: #2563eb;
    }}
    body {{
      font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
      margin: 0;
      background: var(--bg);
      color: var(--fg);
      line-height: 1.55;
    }}
    .wrap {{
      max-width: 980px;
      margin: 0 auto;
      padding: 2rem 1.25rem;
    }}
    a {{ color: var(--link); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    h1 {{ font-size: 2rem; margin: 0 0 1rem; }}
    h2 {{ font-size: 1.5rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); }}
    h3 {{ font-size: 1.15rem; margin-top: 1.5rem; }}
    h4 {{ font-size: 1rem; margin-top: 1.25rem; }}
    p {{ margin: 0.75rem 0; }}
    ul {{ margin: 0.75rem 0 0.75rem 1.25rem; }}
    li {{ margin: 0.25rem 0; }}
    code {{
      background: var(--codebg);
      padding: 0.15rem 0.3rem;
      border-radius: 6px;
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
      font-size: 0.95em;
    }}
    pre {{
      background: var(--codebg);
      padding: 1rem;
      border-radius: 10px;
      overflow: auto;
      border: 1px solid var(--border);
    }}
    pre code {{
      background: transparent;
      padding: 0;
      border-radius: 0;
      font-size: 0.9em;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      margin: 1rem 0;
      border: 1px solid var(--border);
    }}
    th, td {{
      border: 1px solid var(--border);
      padding: 0.5rem 0.6rem;
      text-align: left;
      vertical-align: top;
    }}
    th {{ background: #f9fafb; }}

    /* TOC styling (generated by markdown 'toc' extension) */
    .toc {{
      background: #f9fafb;
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 1rem;
      margin: 1rem 0 2rem;
    }}
    .toc ul {{
      list-style: none;
      margin-left: 0;
      padding-left: 0;
    }}
    .toc li {{
      margin: 0.25rem 0;
    }}
  </style>
</head>
<body>
  <div class="wrap">
    {body}
  </div>
</body>
</html>
"""
